"""
view_constants.py = presentation/layout constants for views

splash timings
menu panel size
button size
menu gap spacing
colors used repeatedly across splash/title/load/settings screens
title text positions
fade durations
"""

from constants import SCREEN_WIDTH

## START SPLASH
SPLASH_FADE_IN_DURATION = 1.2
SPLASH_HOLD_DURATION = 3.2
SPLASH_FADE_OUT_DURATION = 1.0
SPLASH_DONE_HOLD_DURATION = 0.35

SPLASH_BACKGROUND_COLOR = (204, 153, 0)
SPLASH_TOP_TINT = (204, 153, 0)
SPLASH_BOTTOM_TINT = (15, 69, 16)
SPLASH_BASE_FILL = (18, 26, 30)
SPLASH_FRAME_COLOR = (182, 220, 206)
SPLASH_FRAME_FILL = (10, 14, 18)

SPLASH_STUDIO_TEXT = ("Developed by Bayaz")
SPLASH_TEXT_X = SCREEN_WIDTH / 2.55
SPLASH_TEXT_Y = 340
SPLASH_TEXT_SIZE = 28

## MASCOT AND FRAME SIZING
SPLASH_MASCOT_CENTER_X = 900
SPLASH_MASCOT_CENTER_Y = 350
SPLASH_MASCOT_WIDTH = 690
SPLASH_MASCOT_HEIGHT = 690

SPLASH_FRAME_CENTER_X = 900
SPLASH_FRAME_CENTER_Y = 350
SPLASH_FRAME_WIDTH = 330
SPLASH_FRAME_HEIGHT = 330
SPLASH_FRAME_BORDER_WIDTH = 3


## TITLE MENU SCREEN
TITLE_BACKGROUND_COLOR = (182, 220, 206)
TITLE_BG_FILL = (16, 22, 28)
TITLE_BG_BOTTOM_BAND = (204, 153, 0)

MENU_PANEL_WIDTH = 500
MENU_PANEL_HEIGHT = 450
MENU_PANEL_START_Y = -220
MENU_PANEL_SLIDE_DURATION = 0.75

MENU_BUTTON_WIDTH = 250
MENU_BUTTON_HEIGHT = 52
MENU_BUTTON_GAP = 72
MENU_BUTTON_STAGGER = 0.25
MENU_BUTTON_ANIM_DURATION = 0.18
MENU_BUTTON_START_SCALE = 0.86