"""
view_constants.py = presentation/layout constants for views

splash timings
menu panel size
button size
menu gap spacing
colors used repeatedly across splash/title/load/settings screens
title text positions
fade durations
"""

SPLASH_FADE_IN_DURATION = 1.2
SPLASH_HOLD_DURATION = 3.2
SPLASH_FADE_OUT_DURATION = 1.0
SPLASH_DONE_HOLD_DURATION = 0.35

SPLASH_BACKGROUND_COLOR = (8, 12, 16)
SPLASH_TOP_TINT = (28, 40, 48)
SPLASH_BOTTOM_TINT = (22, 34, 28)
SPLASH_BASE_FILL = (18, 26, 30)
SPLASH_FRAME_COLOR = (182, 220, 206)
SPLASH_FRAME_FILL = (10, 14, 18)
SPLASH_TEXT_Y = 135
SPLASH_TEXT_SIZE = 28
SPLASH_MASCOT_BOX_SIZE = 350
SPLASH_MASCOT_FRAME_PADDING = 18

TITLE_BACKGROUND_COLOR = (12, 18, 24)
TITLE_BG_FILL = (16, 22, 28)
TITLE_BG_BOTTOM_BAND = (20, 32, 26)

MENU_PANEL_WIDTH = 500
MENU_PANEL_HEIGHT = 430
MENU_PANEL_START_Y = -250
MENU_PANEL_SLIDE_DURATION = 0.75

MENU_BUTTON_WIDTH = 250
MENU_BUTTON_HEIGHT = 52
MENU_BUTTON_GAP = 72
MENU_BUTTON_STAGGER = 0.14
MENU_BUTTON_ANIM_DURATION = 0.18
MENU_BUTTON_START_SCALE = 0.86