"""
view_constants.py = presentation/layout constants for views

splash timings
menu panel size
button size
menu gap spacing
colors used repeatedly across splash/title/load/settings screens
title text positions
fade durations
"""

from constants import SCREEN_WIDTH

## START SPLASH
SPLASH_FADE_IN_DURATION = 1.2
SPLASH_HOLD_DURATION = 3.2
SPLASH_FADE_OUT_DURATION = 1.0
SPLASH_DONE_HOLD_DURATION = 0.35

# softer placeholder tone that should blend better with a pale maple leaf jpg
SPLASH_BACKGROUND_COLOR = (253, 198, 167)
SPLASH_BASE_FILL = (253, 198, 167)
SPLASH_FRAME_COLOR = (182, 220, 206)
SPLASH_FRAME_FILL = (10, 14, 18)

SPLASH_STUDIO_TEXT = "Developed by   Mourning Man"
SPLASH_TEXT_X = SCREEN_WIDTH / 2.55
SPLASH_TEXT_Y = 340
SPLASH_TEXT_SIZE = 28

## MASCOT AND FRAME SIZING
SPLASH_MASCOT_CENTER_X = 850
SPLASH_MASCOT_CENTER_Y = 350
SPLASH_MASCOT_WIDTH = 690
SPLASH_MASCOT_HEIGHT = 690

SPLASH_FRAME_CENTER_X = 850
SPLASH_FRAME_CENTER_Y = 350
SPLASH_FRAME_WIDTH = 330
SPLASH_FRAME_HEIGHT = 330
SPLASH_FRAME_BORDER_WIDTH = 3

# maple leaf placeholder settings
SPLASH_LEAF_ALPHA = 102
SPLASH_LEAF_MIN_SCALE = 0.01
SPLASH_LEAF_MAX_SCALE = 0.05


## TITLE LINE COLORS
TITLE_BACKGROUND_COLOR = (182, 220, 206)
TITLE_BG_FILL = (16, 82, 28)
TITLE_BG_BOTTOM_BAND = (16, 82, 88)

MENU_PANEL_WIDTH = 500
MENU_PANEL_HEIGHT = 450
MENU_PANEL_START_Y = -220
MENU_PANEL_SLIDE_DURATION = 0.75

MENU_BUTTON_WIDTH = 250
MENU_BUTTON_HEIGHT = 52
MENU_BUTTON_GAP = 72
MENU_BUTTON_STAGGER = 0.25
MENU_BUTTON_ANIM_DURATION = 0.18
MENU_BUTTON_START_SCALE = 0.86
